### ISSUE TITLE
QField doesn´t find a new project

### ISSUE THREAD

**Issue by Karin1964** [opengisch/QField-docs#10] opened 2018-03-20 11:49 UTC
I just installed QField on my Android, QField Sync and QGIS2compat on the notebook and created a project. I copied the project folder in the right folder of the Android, but QField can´t find and open it. It´s not visible in the folder via QField, but if I search for it via  Samsung, I can see it.

**Comment by marioba** [comment] 2019-03-12 07:12
I close this because it's not a QField-doc issue and QField has a completely new file selector now and probably the problem is now fixed.

**Closed by marioba** 2019-03-12 07:12 UTC
